services:
  frontend:
    image: node:23-alpine
    volumes:
      - "./frontend:/app"
    working_dir: /app
    command: npm run dev
    ports:
      - "5173:5173"
    environment:
      VITE_API_ENDPOINT: http://localhost:5123

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile_dev
    volumes:
      - "./backend:/app"
    working_dir: /app
    command: python main.py
    ports:
      - "5123:5123"
