services:
  frontend:
    image: node:23-alpine
    volumes:
      - "./frontend:/app"
    working_dir: /app
    command: npm run dev
    ports:
      - "5173:5173"

  backend:
    build: ./backend/
    volumes:
      - "./backend:/app"
    working_dir: /app
    command: python server.py
    ports:
      - "5123:5123"
